### ISSUE TITLE
It does not work 

### ISSUE THREAD

**Issue by DrooxingJ** [danyildiabin/tiktok-to-discord#1]
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Url.parse (node:url:168:3)
    at Object.urlParse [as parse] (node:url:155:13)
    at dispatchHttpRequest (/home/.algo/tiktok-to-discord/node_modules/axios/lib/adapters/http.js:124:22)
    at new Promise (<anonymous>)
    at httpAdapter (/home/.algo/tiktok-to-discord/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/home/.algo/tiktok-to-discord/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/home/.algo/tiktok-to-discord/node_modules/axios/lib/core/Axios.js:108:15)
    at Axios.<computed> [as get] (/home/.algo/tiktok-to-discord/node_modules/axios/lib/core/Axios.js:129:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by danyildiabin** [comment]
Yes, it stopped working few days ago. I'll check what's wrong tomorrow.

**Comment by danyildiabin** [comment]
Hello, I'm glad to announce that I reworked this project almost from scratch and everything is working again, no patches needed.
Here is a commit if you want to see what changed: accf12c8f9da5e9b8f618b50ff09989c1d9d963d
I'll write new README documentation for this project to help people set everything up because many things have changed and many new features were added.

**Comment by danyildiabin** [comment]
Documentation/Guide updated. Let me know if you have any other problems and feel free to close this issue.
